version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies and executing unit tests - `pwd`"
      - mkdir -p deployment/global-s3-assets
      - mkdir -p deployment/regional-s3-assets
      - mkdir -p deployment/open-source
      - touch deployment/open-source/source-is-on-github
      - pip install ".[dev]"
      - tox -- --cov --cov-report=term-missing --cov-report "xml:deployment/coverage.xml"
      - echo "Installing dependencies and executing unit tests completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - tox -e build
      - mv dist/* deployment/regional-s3-assets
      - npx cdk synth --asset-metadata false --path-metadata false refreezer > deployment/global-s3-assets/refreezer.template
      - echo "Build completed `date`"

  post_build:
    commands:
      - echo "Retrieving next stage buildspec `date` in `pwd`"
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml ../buildspec.yml
      - echo "Retrieving next stage buildspec complete"
      - echo "Post build completed on `date`"

artifacts:
  files:
      - deployment/**/*
      - source/**/*
      - buildspec.yml
      - CHANGELOG.md
      - LICENSE.txt
      - NOTICE.txt
      - README.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - sonar-project.properties
      - .gitignore
