"""
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
"""

import json
from typing import Any, Dict, Callable
from datetime import timedelta
from unittest.mock import patch
from moto import mock_glacier  # type: ignore
import requests  # type: ignore
from refreezer.application.mocking.mock_glacier_vault import MockGlacierVault

mock_vault_list = []


# Decorator to mark a function as a mock vault. Will include a vault with the same name as the function in mock_glacier_data.py
def mock_vault(func: Callable) -> Callable:  # type: ignore
    def wrapper() -> Dict[str, Any]:
        with mock_glacier():
            # Mock timedelta to 0 to avoid sleeping on initiate-job in moto
            with patch("datetime.timedelta", return_value=timedelta(seconds=0)):
                # Seed moto so values are consistent across runs
                requests.post("http://motoapi.amazonaws.com/moto-api/seed?a=1")
                vault = MockGlacierVault(func.__name__)
                func(vault)
                return vault.mock_data()

    mock_vault_list.append(wrapper)


@mock_vault
def vault1(vault: MockGlacierVault) -> None:
    archive_id = vault.upload_archive(body="TESTBODY", archive_description="test.txt")
    inventory_job_id = vault.initiate_job({"Type": "inventory-retrieval"})
    vault.get_job_output(inventory_job_id)

    archive_job_id = vault.initiate_job(
        {"Type": "archive-retrieval", "ArchiveId": archive_id}
    )
    vault.get_job_output(archive_job_id, range="bytes=0-2")
    vault.get_job_output(archive_job_id, range="bytes=3-5")
    vault.get_job_output(archive_job_id, range="bytes=6-8")


@mock_vault
def vault2(vault: MockGlacierVault) -> None:
    archive_id = vault.upload_archive(body="TESTBODY", archive_description="test.txt")
    archive_id_2 = vault.upload_archive(
        body="TESTBODY2", archive_description='my archive description,1"2'
    )
    inventory_job_id = vault.initiate_job({"Type": "inventory-retrieval"})
    vault.get_job_output(inventory_job_id)

    archive_job_id = vault.initiate_job(
        {"Type": "archive-retrieval", "ArchiveId": archive_id}
    )

    archive_2_job_id = vault.initiate_job(
        {"Type": "archive-retrieval", "ArchiveId": archive_id_2}
    )
    vault.get_job_output(archive_job_id, range="bytes=0-2")
    vault.get_job_output(archive_job_id, range="bytes=3-5")
    vault.get_job_output(archive_job_id, range="bytes=6-8")
    vault.get_job_output(archive_2_job_id)


if __name__ == "__main__":
    mock_vault_dict: Dict[str, Any] = {}
    for mock_vault in mock_vault_list:  # type: ignore
        mock_vault_dict = mock_vault_dict | mock_vault()  # type: ignore
    with open("mock_glacier_data.py", "w") as f:
        f.write(
            '"""\nCopyright Amazon.com, Inc. or its affiliates. All Rights Reserved.\nSPDX-License-Identifier: Apache-2.0\n"""\n'
        )
        f.write(
            "# This file is auto-generated by mock_glacier_generator.py and formatted with black\n"
        )
        f.write(f"MOCK_DATA = {json.dumps(mock_vault_dict, indent=4)}")
